apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: registry.cn-shanghai.aliyuncs.com/yushi-docker/aliyun-test:nodejsrest1.0.2 # replace it with your exactly <image_name:tags>
       
      imagePullSecrets:          #Comment out to enable specific image pull secret
      - name: regcred    # repleace it wity your specific docker registry secret
      # alternative way to set this field of imagePullSecrets can be automated by setting the imagePullSecrets in a serviceAccount resource
#      serviceAccountName: user1
#      automountServiceAccountToken: false